config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: 'home#index'


  match 'user_root' => 'users#profile', :via => [:get]
  resources :dishes

  resources :events

  get '/dishes/new/event/:id', to: "dishes#new", as: 'new_dish_event'

  post '/dishes', to: "dishes#create"

  match '/users/:id',     to: 'users#show',       via: 'get'

  # devise_for :users, :path_prefix => 'd'

  resources :users, :only =>[:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/puppy_recipe_api.rb
module PuppyRecipeApi
  BASE_URL = 'http://www.recipepuppy.com/api/'

  def self.query(user_query_params)
    query =  "#{BASE_URL}"
    search_format = "?q=#{user_query_params.gsub(' ', '%20')}"
    response_thing = RestClient.get(query+search_format)
    parsed_response = JSON.parse(response_thing)

    results = parsed_response["results"]
  end 
end 

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :name, presence: true
  accepts_nested_attributes_for :user
  # attr_accessible :name, :description

  extend PuppyRecipeApi
end

app/models/event.rb
class Event < ApplicationRecord
  # Associations
  has_many :event_users
  has_many :users, through: :event_users
  has_many :dishes
  has_many :users, through: :dishes

  # Validation
  validates_presence_of :name, on: :create, message: "Please pick a name for your potluck"
  validates_presence_of :date, on: :create, message: "Please pick a date for your potluck"
  validates_presence_of :time, on: :create, message: "Please pick a time for your potluck"
  validates_presence_of :location, on: :create, message: "Please pick a location for your potluck"

  def format_time(event)
    formatted_time = DateTime.parse("#{event[:hour]}:#{event[:minute]}#{event[:meridiem]}")
    self.time = formatted_time.strftime("%I:%M%p")
    self.save
  end

  # Class method Search
  def self.search(search)

    if search
      self.where("location LIKE ?", "%#{search}%")
    else
      Event.all
    end
  end
  

end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/noavatar.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
    
  has_many :event_users
  has_many :events, through: :event_users
  has_many :dishes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def current_user
  #   @dish.user = current_user
  #   @dish = current_user.dishes.new(params[:dish])
  # end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :find_dish, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create,:edit,:destroy]

  def index
    @dishes = Dish.all
  end

  def show
    # before_action finds the instance
    @recipe_results = PuppyRecipeApi.query(@dish.name)

  end

  def edit
    # before_action finds the instance
  end

  def update
    # before_action finds the instance
    @dish.update(dish_params)
    redirect_to @dish
  end

  def destroy
    # before_action finds the instance
    @dish.destroy
    redirect_to events_path
  end

  def new
    @dish = Dish.new
    # render :new
  end

  def create
    @event = Event.find_by(id: params[:id])
    @dish = Dish.new(dish_params)
    # byebug
    if @dish.valid?
      @dish.save
      redirect_to event_path(@dish.event_id)
    else
      flash[:errors] = @dish.errors.full_messages
      redirect_to new_dish_path
    end
  end


  private

  def dish_params
    params.require(:dish).permit(:name, :description, :event_id, :user_id)
  end

  def find_dish
    @dish = Dish.find_by(id: params[:id])
  end
end # end of controller

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :find_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new, :create,:edit,:destroy]
  

  # def index
  #   @events = Event.all
  #   #TODO Search function
  # end 

  def index 
    @events = Event.search(params[:search])
  end

  def new
    @event = Event.new
  end

  def show
    # before_action finds the instance
  end

  def time_format(string)
    string.strftime()
  end

  def create
    @user = current_user
    @event = Event.new(event_params)
    @event.user_host_id = @user.id
    @event.format_time(params[:event])
    # @event.user  = current_user #that devise magic
    if @event.valid?
      @event.save
      @event_user = EventUser.create(event_id: @event.id, user_id: current_user.id)
      redirect_to @event
    else
      flash[:errors] = @event.errors.full_messages
      redirect_to new_event_path
    end
  end

  def edit
    # before_action finds the instance
  end

  def update
    # before_action finds the instance
    @event.update(event_params)
    redirect_to @event
  end

  def destroy
    if @event.user_host_id == current_user.id
      @event.destroy    
      redirect_to events_path
    else 
      redirect_to events_path
    end 
  end

  private

    def event_params
      params.require(:event).permit(:name,:date,:description,:location, :user_host_id,:search)
    end

    def find_event
      @event = Event.find_by(id: params[:id])
    end

end # END OF EVENTS CONTROLLER

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # render 'index'
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :bio, :location, :avatar, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :bio, :location,:avatar, :email, :password, :password_confirmation, :current_password)
  end

  def after_update_path_for(resource)
    user_root_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :find_user, only: [:edit, :update, :show]
  before_action :find_user, only: [:show]

  def show
    # before_action finds the instance
  end

  def new
    @user = User.new
  end

  def create
   @user = User.create(user_params)
    #TODO Add validation
  end

  def profile
    current_user 
  end

  private

    def find_user
      @user = User.find_by(id: params[:id])
    end

    def user_params
      params.require(:user).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dishes/_form.html.erb
<div class="form-outer-container">
  <%= form_for @dish do |f| %>
    <%= f.label :dish_name %>
    <%= f.text_field :name %>

    <%= f.label :dishcription %>
    <%= f.text_area :description %>
    <%= f.hidden_field :event_id, :value => params[:id] %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "Submit Your Dish!", class: "new-action-button" %>
  <% end %>
</div>

app/views/dishes/edit.html.erb
<div class="form-wrapper">
  <h1>Edit dish</h1>
  <%= render 'form' %>

  <%= button_to "Delete that dish", @dish, :method => :delete, class: "delete-button"%>

</div>

app/views/dishes/index.html.erb
<h1>All dem dishez</h1>

<% @dishes.each do |dish| %>
  <%= dish.name %> <br>
<% end %>

app/views/dishes/new.html.erb
<div class="form-wrapper">
  <h1>What dish are you bringing?</h1>
  <% if flash[:errors] %>
    <% flash[:errors].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>

  <%= render 'form' %>
</div>

app/views/dishes/show.html.erb
<div class="profile-card-outer-container dish-outer-container">
  <% if user_signed_in? && current_user.dishes.include?(@dish) %>
    <%= button_to "Delete this dish", @dish, class: "delete-button", :method => :delete%>
  <% end %>

  <div class="dish-recipes">
    <h1>Recipe Suggestions for <%= @dish.name %>:</h1>

    <% @recipe_results.each do |recipe| %>
      <%= link_to recipe["href"], class: "event-card dish" do %>
        <div class="event-content dish-content">
          <h1 class="dish-title">
            <%= recipe["title"] %>
          </h1>
          <div class="title-separator"></div>
          <div class="ingredients-container">
            <% recipe["ingredients"].split(",").each do |ingredient| %>
              <h4 class="recipe-ingredient"><%= ingredient %></h4>
            <% end %>
          </div>
        </div>
      <% end  %>
    <% end %>
  </div>
</div>

app/views/events/_form.erb
<div class="form-outer-container">
  <%= simple_form_for @event do |f| %>
    <%= f.input :name, label:'Name :' %>
    <%= f.input :date, label:'Date :', as: :date, 
                start_year: Date.today.year, 
                end_year: Date.today.year + 15, 
                order: [:month,:year,:day] 
    %>                                           
    <div class="timepicker">
      <%= f.label :time, label: 'Time :' %>
      <select class="hour form-control" name="event[hour]">
        <%= options_for_select((1..12).to_a, @event.time ? @event.time.strftime('%l').to_i : nil) %>
      </select>
      <span class="colon">:</span>
      <select class="minute form-control" name="event[minute]" >
        <%= options_for_select(['00', '15', '30', '45'], @event.time ? @event.time.strftime('%M').to_i : nil) %>
      </select>
      <select class="meridiem form-control" name="event[meridiem]" >
        <%= options_for_select(['AM', 'PM'], @event.time ? @event.time.strftime('%p') : nil) %>
      </select>
    </div>
    <%= f.input :description, label:'Description :' %>
    <%= f.input :location %>
    <%= f.button :submit, class: "new-action-button" %>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="form-wrapper">
  <h1>Edit/Update Your Potlucks</h1>
  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<div class="potluck-events-container">
  <h1>All Potlucks</h1>

<%# SEARCH! %>
  <div class="search-container">
    <%= form_tag(events_path, method: :get) do %>
    <%= label_tag(:location, "Search by Location:") %>
    <div class="search-inner-container">
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Search", class: "search-button") %>
    </div>
    <% end %>
  </div>

<%# EVENT LIST! %>
<% @events.each do |event| %>
    <%= link_to event, class: "event-card" do %>
      <div class="event-content">
        <p class="event-name">
          <%= event.name %>
        </p>
        <ul>
          <li>
            <%= fa_icon "calendar" %>
            <%= event.date %>
          </li>
          <li>
            <%= fa_icon "user-clock" %>
            <%= event.time %>
          </li>
          <li><%= event.location %></li>
        </ul>
        <div class="user-thumbnails">
          <% event.users.uniq.each do |user| %>
            <div class="thumbnail">
              <%= image_tag(user.avatar.url(:thumb), :class => "avatar-image") %>
            </div>
          <% end %>
        </div>
      </div>
    <% end  %>
  <% end %>
</div>

<!-- check out https://www.groupmuse.com/calendar as style guide -->

app/views/events/new.html.erb
<div class="form-wrapper">
  <h1>Create a New Potluck</h1>
  <%=render 'form' %>
</div>

app/views/events/show.html.erb
<div class="potluck-events-container">
  <div class="show-container form-wrapper">
    <h1><%= @event.name %> </h1>

    <h4> Date: <%= @event.date %></h4>
    <h4>Time: <%= @event.time %></h4>
    <h4>Description: <%= @event.description %></h4>
    <h4>Location: <%= @event.location %></h4>
    <table class="potluck-table">
      <thead>
        <tr>
          <th>Attendees</th>
          <th>Dishes</th>
        </tr>
      </thead>
      <tbody>
        <% @event.users.uniq.each do |potluck_attendee| %>
          <tr>
            <td><%= link_to potluck_attendee.name, potluck_attendee %></td>
            <td>
              <% potluck_attendee.dishes.each do |dish| %>
                <% if dish.event_id == @event.id %>
                <%= link_to dish.name, dish %>
                <span class="comma-separator">,</span>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="form-actions">
      <% if user_signed_in? && current_user.id == @event.user_host_id %>
        <%= button_to "Delete Potluck", @event, :method => :delete, class: "delete-button" %>
      <% end %>
      <!-- hide this button if current user is not host  -->
      <% if user_signed_in? %>
        <%= link_to "Join Event", new_dish_event_path(@event), class: "new-action-button" %>
      <% else %>
        <%= link_to "Sign In to Join Event", new_user_session_path, class: "new-action-button" %>
      <% end %>
    </div>

    <!-- this link should show if youre joined already -->
  </div>
</div>

app/views/home/index.html.erb
<div class="home-container">
<!-- <img src="/assets/transparent_logo.png" alt="" class="potluck-logo"> -->
  <div class="potluck-logo">
    <%= image_tag "transparent_logo.png"%>
  </div>
  <div class="button-container">
    <div class="new-action-button warm">
      <%= link_to "Check Out All Potlucks", events_path %>
    </div>
    <div class="new-action-button warm">
        <%= link_to "Make Your Own Potluck", new_event_path %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-links">
  <div class="logo-container">  
    <div class="potluck-logo">
      <%= link_to root_path do %>
        <%= image_tag "transparent_logo.png"%>
      <%end%>
    </div>
  </div>

  <!-- <div class="page-link-container">
    <%= link_to "Events", events_path, class: "page-link" %>
    <%= link_to "About", root_path, class: "page-link" %>
  </div> -->
  <div class="registration-links">
    <%= link_to "Events", events_path, class: "navbar-link" %>
    <% if user_signed_in? %>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% if current_user.avatar %>
        <%= link_to user_root_path do %>
          <%= image_tag(current_user.avatar.url(:thumb), :class => "avatar-image")%>
        <% end %>
      <% end  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potluck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <!-- <div class="overlay"></div> -->
    <div class="body-content-container">
      <div class="navbar">
        <%= render partial: "/layouts/navbar" %>
      </div>
      <div class="body-inner-container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/profile.html.erb
<div class="profile-card-outer-container">
  <h1>My Profile</h1>
  <div class="profile-card-container">
    <div class="profile-image-container">
        <%= image_tag(current_user.avatar.url(:thumb), :class => "avatar-image") %>
    </div>
    <div class="profile-info-container">
      <h4>Name: <%= current_user.name %> </h4>
      <h4>Email: <%= current_user.email %> </h4>
      <h4>Location: <%= current_user.location %></h4>
    </div>
  </div>
  <div class="profile-body-container">

      <h4>About:
        <p><%= current_user.bio %>
              <!-- start slipsum code -->
        </p>
      </h4>
  
  </div>
  <div class="user-events">
    <h1>My Events</h1>
    <% current_user.events.each do |event| %>
      <%= link_to event, class: "event-card" do %>
        <div class="event-content user-content">
          <p class="event-name">
            <%= event.name %>
          </p>
          <ul>
            <li>
              <!-- <%= fa_icon "camera-retro" %> -->
              <%= fa_icon "calendar" %>
              <%= event.date %>
            </li>
            <li>
              <%= event.time %>
            </li>
            <li><%= event.location %></li>
          </ul>
          <div class="user-thumbnails">
            <% event.users.uniq.each do |user| %>
              <div class="thumbnail">
                <%= image_tag(user.avatar.url(:thumb), :class => "avatar-image") %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="new-action-button">
    <%= link_to "Create a new potluck", new_event_path %>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "new-action-button" %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "new-action-button" %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="profile-card-outer-container">
  <h1><%= @user.name %>'s Profile</h1>
  <div class="profile-card-container">
    <div class="profile-image-container">
        <%= image_tag(@user.avatar.url(:thumb), :class => "avatar-image") %>
    </div>
    <div class="profile-info-container">
      <h4>Name: <%= @user.name %> </h4>
      <h4>Email: <%= @user.email %> </h4>
      <h4>Location: <%= @user.location %></h4>
    </div>
  </div>
  <div class="profile-body-container">
    <h4>About:
      <p><%= @user.bio %>
            
      </p>
    </h4>
  </div>
  <div class="user-events">
    <h1><%= @user.name %>'s Events</h1>
    <% @user.events.each do |event| %>
      <%= link_to event, class: "event-card" do %>
        <div class="event-content user-content">
          <p class="event-name">
            <%= event.name %>
          </p>
          <ul>
            <li>
              <!-- <%= fa_icon "camera-retro" %> -->
              <%= fa_icon "calendar" %>
              <%= event.date %>
            </li>
            <li>
              <%= event.time %>
            </li>
            <li><%= event.location %></li>
          </ul>
          <div class="user-thumbnails">
            <% event.users.uniq.each do |user| %>
              <div class="thumbnail">
                <%= image_tag(user.avatar.url(:thumb), :class => "avatar-image") %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>